### ISSUE TITLE
Lambda authorizers not created if properties missing

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-aws-apigateway#10]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

If `authType` isn't set to 'custom', the deployment will succeed, but no authorization will be applied. This is mapped to the `x-amazon-apigateway-authtype` property.

### Steps to reproduce

```typescript
const api = new apigateway.RestAPI("api", {
    routes: [{
        path: "/",
        localPath: "www",
        // Define an authorizer which uses Lambda to validate the token from the Authorization header
        authorizers: [{
            authType: "custom",// <- if this property is not defined, authorization will be removed siliently
            parameterName: "Authorization",
            type: "request",
            identitySource: ["method.request.header.Authorization"],
            handler: authLambda,
        }]
    }],
});
```

Expected: Deployment should not succeed.
Actual: Deployment succeeds but no authorizers are applied.

**Comment by lukehoban** [comment]
It looks like perhaps this is the same issue as tracked in https://github.com/pulumi/pulumi-awsx/issues/564?

**Comment by danielrbradley** [comment]
Closing as duplicate of https://github.com/pulumi/pulumi-awsx/issues/564
