### ISSUE TITLE
Add the possibility to Tag ApiGateway

### ISSUE THREAD

**Issue by MarcoMarinoniMoov** [pulumi/pulumi-aws-apigateway#139]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I'm trying to create an API Gateway with this plugin, and it's all super easy and convenient. I only noticed that tagging is not supported. 
Since this plugin uses the pulumi-aws package, I suppose this can be done easily. Can you consider adding it in future releases?

**Comment by mjeffryes** [comment]
Thanks for the suggestion @MarcoMarinoniMoov. It should be possible to add tags using [transformations](https://www.pulumi.com/docs/concepts/options/transformations/) today, but I agree that it would be nice if we exposed tags on the component resource itself.
