### ISSUE TITLE
Update AWSX version to a non-alpha version

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws-apigateway#57]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Currently it's using AWSX version `^0.32.1-alpha.1634010693`. It should be at least the 0.4.0 version.

**Comment by viveklak** [comment]
Thanks @pierskarsenbarg. @danielrbradley can this be scheduled? Sounds like we should be able to use 0.40.0 at least?

**Comment by catmeme** [comment]
`@pulumi/aws` MAJOR version is upgraded in 0.40.0

* https://github.com/pulumi/pulumi-awsx/blob/v0.33.0/nodejs/awsx/package.json#L22
* https://github.com/pulumi/pulumi-awsx/blob/v0.40.0/nodejs/awsx/package.json#L22
