### ISSUE TITLE
Go SDK installation fails

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-aws-apigateway#67]
### What happened?

Adding `github.com/pulumi/pulumi-aws-apigateway/sdk v1.0.0` fails.

```
go: downloading github.com/pulumi/pulumi-aws-apigateway/sdk v1.0.0
module github.com/pulumi/pulumi-aws-apigateway/sdk@latest found (v1.0.0), but does not contain package github.com/pulumi/pulumi-aws-apigateway/sdk/apigateway/index
```

### Steps to reproduce

```
pulumi convert --language go
```

or 

1. Add `github.com/pulumi/pulumi-aws-apigateway/sdk v1.0.0` to `go.mod`.
2. `go mod tidy`

### Expected Behavior

Dependency installation should pass

### Actual Behavior

Dependency resolution fails

### Output of `pulumi about`

```
CLI          
Version      3.47.1
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME            VERSION
aws             unknown
aws-apigateway  unknown
yaml            unknown

Host     
OS       darwin
Version  13.0.1
Arch     arm64

Current Stack: dev

Found no resources associated with dev

Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/daniel-pulumi
User           daniel-pulumi
Organizations  daniel-pulumi, pulumi

Pulumi locates its logs in /var/folders/40/n23_nmpj47n3fxxpqls5h9tw0000gn/T/ by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lukehoban** [comment]
I can't reproduce this, on either `v1.0.0` or current `v2.0.1`.
