### ISSUE TITLE
Unable to run the plugin in WSL v1

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/pulumi-aws-apigateway#73]
### What happened?

Failing with this error:

```
pulumi:providers:aws-apigateway (default_1_0_1)
    error: failed to load plugin /home/**/.pulumi/plugins/resource-aws-apigateway-v1.0.1/pulumi-resource-aws-apigateway: fork/exec /home/**/.pulumi/plugins/resource-aws-apigateway-v1.0.1/pulumi-resource-aws-apigateway: exec format error
```

when running the provider binary (so `./pulumi-resource-aws-apigateway`) user gets this response:

![image](https://github.com/pulumi/pulumi-aws-apigateway/assets/109047/652c3d10-8baa-42ce-9efb-f0f893f18c2f)

`file ./pulumi-resource-aws-apigateway` gives the following response:

![image](https://github.com/pulumi/pulumi-aws-apigateway/assets/109047/baa20721-0c79-4bc0-afeb-83746c7b9bea)

### Expected Behavior

`pulumi up` works and is able to find the provider.

### Steps to reproduce

Can't reproduce at the moment.

### Output of `pulumi about`

```
pulumi about                                                                                                                                          CLI
Version      3.65.1
Go Version   go1.20.3
Go Compiler  gc
Plugins
NAME            VERSION
aws             5.40.0
aws-apigateway  1.0.1
awsx            1.0.2
docker          3.6.1
nodejs          unknown
Host
OS       ubuntu
Version  20.04
Arch     x86_64
This project is written in nodejs:
executable='/home/***/.nvm/versions/node/v18.16.0/bin/node' version='v18.16.0'
Current Stack: ***/my-serverless-app/dev
Found no resources associated with ***/dev
Found no pending operations associated with ***/dev
Backend
Name           [pulumi.com](http://pulumi.com/)
URL            https://app.pulumi.com/***
User           smriti
Organizations  smriti, ***
Dependencies:                                                                                                                                                                                 NAME                    VERSION
@pulumi/aws             5.40.0
@pulumi/awsx            1.0.2
@pulumi/pulumi          3.67.0
@types/node             16.18.29
typescript              4.9.5
@pulumi/aws-apigateway  1.0.1
Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by pierskarsenbarg** [comment]
I asked the user to do two things:

1. Download resource from GitHub and run that:
![image](https://github.com/pulumi/pulumi-aws-apigateway/assets/109047/6e439719-3835-45d9-8677-b601cebc9183)

2. Follow these steps: 
- `rm ~/my-serverless-app`
- `pulumi plugin rm resource aws-apigateway`
- `mkdir ~/my-serverless-app`
- `cd ~/my-serverless-app`
- `pulumi new serverless-aws-typescript`
- `pulumi preview`

Didn't fix the issue

**Comment by pierskarsenbarg** [comment]
Also, user is using WSLv1 s we've advised to update to v2

**Comment by kpitzen** [comment]
There are quite a few known issues with WSL v1 - exec formats being very high on the list of common issues. We can certainly look into this, but WSL v2 is the current supported version.

**Comment by pierskarsenbarg** [comment]
Just so this is public, the customer updated to WSL v2 and it worked. Not sure if this ticket should be closed or not with that knowledge?

**Comment by pierskarsenbarg** [comment]
Closing as the guidelines should be "update to v2 of WSL"
