### ISSUE TITLE
Incorrect peer dependency on @pulumi/pulumi

### ISSUE THREAD

**Issue by danielrbradley** [pulumi/pulumi-aws-apigateway#8]
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

```
warning " > @pulumi/aws-apigateway@0.0.4" has incorrect peer dependency "@pulumi/pulumi@latest".
```

I think the issue here is that we're specify `@latest` for the version. This version should probably be a valid range specifying instead such as `^3.3.1`.

### Steps to reproduce

1. Create node project
2. Add dependencies `yarn add @pulumi/pulumi @pulumi/aws-apigateway` 

Expected: Should complete without warnings or errors
Actual: Prints peer dependency warning

**Comment by stack72** [comment]
@danielrbradley I am pretty sure we don't have this issue anymore since moving to pkg right?

**Comment by danielrbradley** [comment]
Don't think that affects it - this just relates to the peerDependency in the package.json of the SDK rather than the provider.
