### ISSUE TITLE
Add upgrade tests

### ISSUE THREAD

**Issue by mnlumi** [pulumi/pulumi-aws-apigateway#96]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

Add tests to validate behavior of existing resources as they are upgraded between versions, especially major version changes. Tests should target the key components prioritized by popularity and usage.

**Comment by lukehoban** [comment]
Fixed by https://github.com/pulumi/pulumi-aws-apigateway/pull/101.
